version: '2'

volumes:
  pg-data:

services:
  jeeves:
    build: .
    volumes:
      - .:/jeeves
      - /jeeves/node_modules

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
